# Generated by Django 5.1.7 on 2025-03-14 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Enter the title of the news article", max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Enter the full text of the news article", verbose_name="Content"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the news article was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the news article was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time when the news article was published",
                        null=True,
                        verbose_name="Published At",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of likes recieved by the news article", verbose_name="View Count"
                    ),
                ),
                (
                    "like_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of likes received by the news article.", verbose_name="Like Count"
                    ),
                ),
                (
                    "dislike_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of dislikes received by the news article.",
                        verbose_name="Dislike Count",
                    ),
                ),
            ],
            options={
                "verbose_name": "News",
                "verbose_name_plural": "News",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Unique tag for news category", max_length=50, unique=True, verbose_name="Tag Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NewsImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload an image for the news article", upload_to="news_images/", verbose_name="Image"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Optional caption for the image",
                        max_length=255,
                        null=True,
                        verbose_name="Caption",
                    ),
                ),
                (
                    "news",
                    models.ForeignKey(
                        help_text="The news article this image belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="news.news",
                        verbose_name="News Article",
                    ),
                ),
            ],
            options={
                "verbose_name": "News Image",
                "verbose_name_plural": "News Images",
            },
        ),
        migrations.AddField(
            model_name="news",
            name="tags",
            field=models.ManyToManyField(
                help_text="Tags associated with this news article.",
                related_name="news",
                to="news.tag",
                verbose_name="Tags",
            ),
        ),
    ]
