# Generated by Django 5.1.7 on 2025-03-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="slug",
            field=models.SlugField(default="", help_text="SEO-friendly URL identifier", max_length=220, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="news",
            index=models.Index(fields=["slug"], name="news_news_slug_915ecd_idx"),
        ),
        migrations.AddIndex(
            model_name="news",
            index=models.Index(fields=["published_at"], name="news_news_publish_377f0e_idx"),
        ),
    ]
