# Generated by Django 5.1.7 on 2025-03-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_news_slug_news_news_news_slug_915ecd_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="featured_image",
            field=models.ImageField(
                default="",
                help_text="Upload the featured image for the news article",
                upload_to="news_images/featured_images/",
                verbose_name="Image",
            ),
            preserve_default=False,
        ),
    ]
