# Generated by Django 5.1.7 on 2025-03-15 17:56

from django.db import migrations, models

import apps.news.models.news
import apps.news.models.news_image


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_news_featured_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"ordering": ["-created_at"], "verbose_name": "News", "verbose_name_plural": "News"},
        ),
        migrations.AddField(
            model_name="news",
            name="status",
            field=models.CharField(
                choices=[("Draft", "Draft"), ("Published", "Published")],
                default="Draft",
                help_text="The current status of the news item",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="featured_image",
            field=models.ImageField(
                help_text="Upload the featured image for the news article",
                upload_to=apps.news.models.news.news_featured_image_path,
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="newsimage",
            name="image",
            field=models.ImageField(
                help_text="Upload an image for the news article",
                upload_to=apps.news.models.news_image.news_image_upload_path,
                verbose_name="Image",
            ),
        ),
    ]
